controller_frequency: 20.0
ChannelController:
  safe_waypoint_channel_width: 0.6
  safe_channel_width: 0.5

  min_get_to_safe_dist_time: 3.0
  max_get_to_safe_dist_time: 10.0

  waypoint_reached_dist: 0.3
  waypoint_reached_angle: 7.0

  goal_reached_dist: 0.1
  goal_reached_angle: 0.087266

  min_tv: 0.08
  max_tv: 1.0
  min_rv: 0.0
  max_rv: 3.5
  min_inplace_rv: 0.35

  stopped_tv: 0.05
  stopped_rv: 0.1

  max_accel_tv: 2.0
  max_accel_rv: 2.3

  wait_for_obstacles_time: 15.0
  no_progress_hard_clear_time: 10.0

  visualize_voronoi: false

