footprint: [[0.3, 0.25], [0.3, -0.25], [-0.3, -0.25], [-0.3, 0.25]]

inflation_layer:
  inflation_radius: 1.00

obstacle_layer:
  observation_sources: laser
  laser: {
    data_type: LaserScan, 
    topic: base_scan, 
    marking: true, 
    clearing: true, 
    min_obstacle_height: 0, 
    max_obstacle_height: 0.5
  }
  

