dynamixel_manager:
    namespace: dxl_manager
    serial_ports:
        cube_gripper_port:
            port_name: "/dev/sensors/serial_port"
            baud_rate: 1000000
            min_motor_id: 1
            max_motor_id: 25
            update_rate: 20

grab_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: cube_gripper_grab_motor_joint
    joint_speed: 1.17
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

lift_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: cube_gripper_lift_motor_joint
    joint_speed: 0.6
    motor_master:
        id: 3
        init: 512
        min: 0
        max: 1023
    motor_slave:
        id: 2
        calibration_offset: 20
