# Default parameters used by the yocs_velocity_smoother module.
# This isn't used by minimal.launch per se, rather by everything
# which runs on top.

# Mandatory parameters
speed_lim_v: 2.0
speed_lim_w: 10.8 

accel_lim_v: 4.0 
accel_lim_w: 8.0

# Optional parameters
frequency: 40.0
decel_factor: 1.5

# Robot velocity feedback type:
#  0 - none (default)
#  1 - odometry
#  2 - end robot commands
robot_feedback: 0
